name: healsense
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  badges: ^3.1.2
  cupertino_icons: ^1.0.8
  drift: ^2.3.0
  equatable: ^2.0.5
  fimber: ^0.7.0
  flutter_local_notifications: ^17.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg_provider: ^1.0.7
  fpdart: ^0.4.0
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  go_router: ^14.2.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  nil: ^1.1.1
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^1.0.6
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.24
  timezone: ^0.9.4
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.3.3
  flutter_config: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.8.0
  riverpod_generator: ^1.0.6
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sliders/
    - assets/images/pharmacy_illustrations/
    - assets/icons/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
